#!/usr/bin/env python3
"""
03_NonLinDistOsc_audiotest_model.py
====================================
Generates 5-second audio files to compare:
  1. target_audio.wav - generated by the target mathematical function
  2. model_audio.wav - generated by the neural model oscillator_v2.ts

Usage:
  conda run -n pytorch313 python 03_NonLinDistOsc_audiotest_model.py

Output:
  - target_audio.wav (5s @ 48kHz)
  - model_audio.wav (5s @ 48kHz)
  - Comparison metrics (MSE, MAE, spectral difference)
"""
import math
import numpy as np
import torch
import scipy.io.wavfile as wavfile

FS = 48000.0  # Hz
DURATION = 5.0  # seconds


def generate_sample_target(freq_hz, amp, distortion_0_100, bias, phase_norm):
    """Target function: generates ONE sample from the non-linear oscillator."""
    phi = 2 * math.pi * phase_norm
    gain = 1 + 9 * (distortion_0_100 / 100.0)
    return amp * math.tanh(gain * math.sin(phi)) + bias


def generate_audio_from_target(freq_hz, amp, dist_pct, bias, duration_sec, fs):
    """Generates complete audio using the target function."""
    n_samples = int(duration_sec * fs)
    audio = np.zeros(n_samples, dtype=np.float64)
    
    phase = 0.0
    phase_inc = freq_hz / fs
    
    for i in range(n_samples):
        phase_norm = phase % 1.0
        audio[i] = generate_sample_target(freq_hz, amp, dist_pct, bias, phase_norm)
        phase += phase_inc
    
    return audio


def generate_audio_from_model(model_path, freq_hz, amp, dist_pct, bias, duration_sec, fs):
    """Generates complete audio using the neural model."""
    model = torch.jit.load(model_path)
    model.eval()
    
    n_samples = int(duration_sec * fs)
    audio = np.zeros(n_samples, dtype=np.float64)
    
    phase = 0.0
    phase_inc = freq_hz / fs
    
    with torch.no_grad():
        for i in range(n_samples):
            phase_norm = phase % 1.0
            inp = torch.tensor([[freq_hz, amp, dist_pct, bias, float(phase_norm)]], dtype=torch.float32)
            audio[i] = model(inp)[0, 0].item()
            phase += phase_inc
    
    return audio


def compute_metrics(target, model_output):
    """Computes comparison metrics between target and model."""
    mse = np.mean((target - model_output) ** 2)
    mae = np.mean(np.abs(target - model_output))
    max_error = np.max(np.abs(target - model_output))
    
    # Spectral difference (spectrum magnitude)
    target_fft = np.abs(np.fft.rfft(target))
    model_fft = np.abs(np.fft.rfft(model_output))
    spectral_diff = np.mean(np.abs(target_fft - model_fft))
    
    return {
        'mse': mse,
        'mae': mae,
        'max_error': max_error,
        'spectral_diff': spectral_diff
    }


def main():
    print("=" * 70)
    print("Audio Test: Non-Linear Oscillator")
    print("=" * 70)
    
    # Oscillator parameters
    freq_hz = 220.0  # Low A
    amp = 0.8
    dist_pct = 90.0  # moderate distortion
    bias = 0.0
    
    print(f"\nParameters:")
    print(f"  Frequency: {freq_hz} Hz")
    print(f"  Amplitude: {amp}")
    print(f"  Distortion: {dist_pct}%")
    print(f"  Bias: {bias}")
    print(f"  Duration: {DURATION}s @ {FS:.0f} Hz")
    print(f"  Total samples: {int(DURATION * FS)}")
    
    # Generate audio with target function
    print("\n1. Generating audio with target function...")
    target_audio = generate_audio_from_target(freq_hz, amp, dist_pct, bias, DURATION, FS)
    print(f"   ✓ Generated: {len(target_audio)} samples")
    print(f"   Range: [{target_audio.min():.4f}, {target_audio.max():.4f}]")
    
    # Generate audio with neural model
    print("\n2. Generating audio with neural model...")
    model_audio = generate_audio_from_model('oscillator_v2.ts', freq_hz, amp, dist_pct, bias, DURATION, FS)
    print(f"   ✓ Generated: {len(model_audio)} samples")
    print(f"   Range: [{model_audio.min():.4f}, {model_audio.max():.4f}]")
    
    # Compute metrics
    print("\n3. Comparing audios...")
    metrics = compute_metrics(target_audio, model_audio)
    print(f"   MSE:             {metrics['mse']:.8f}")
    print(f"   MAE:             {metrics['mae']:.6f}")
    print(f"   Max error:       {metrics['max_error']:.6f}")
    print(f"   Spectral diff:   {metrics['spectral_diff']:.6f}")
    
    # Save WAV files (normalize to int16)
    print("\n4. Saving WAV files...")
    
    # Normalize and convert to int16
    def to_int16(audio):
        # Ensure it's in the range [-1, 1]
        audio_norm = audio / (np.max(np.abs(audio)) + 1e-8)
        # Convert to int16
        return (audio_norm * 32767).astype(np.int16)
    
    target_int16 = to_int16(target_audio)
    model_int16 = to_int16(model_audio)
    
    wavfile.write('target_audio.wav', int(FS), target_int16)
    wavfile.write('model_audio.wav', int(FS), model_int16)
    
    print(f"   ✓ Saved: target_audio.wav")
    print(f"   ✓ Saved: model_audio.wav")
    
    # Qualitative analysis
    print("\n" + "=" * 70)
    print("ANALYSIS:")
    if metrics['mae'] < 0.01:
        print("  ✅ Excellent: Average error < 0.01 (almost imperceptible)")
    elif metrics['mae'] < 0.05:
        print("  ✅ Very good: Average error < 0.05 (subtle difference)")
    elif metrics['mae'] < 0.1:
        print("  ⚠️  Fair: Average error < 0.1 (perceptible difference)")
    else:
        print("  ❌ High error: Significant difference between target and model")
    
    print("\nRecommendation:")
    print("  Listen to target_audio.wav and model_audio.wav files")
    print("  to evaluate the perceptual quality of the model!")
    print("=" * 70)


if __name__ == "__main__":
    main()
